version: "3"

services:
  api:
    build: ./back-end
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=mongodb://mongodb:27017

  mongodb:
    build: ./back-end/mongo_image
    ports:
      - "27017:27017"

  blue-vending-app:
    build: ./blue-vending-app
    ports:
      - "3000:3000"
