db.products.insertMany([
  {
    productId: NumberInt(1),
    name: "Coke",
    qty: NumberInt(10),
    price: NumberInt(72),
    imgSource: "/Coke.png",
  },
  {
    productId: NumberInt(2),
    name: "Redbull",
    qty: NumberInt(12),
    price: NumberInt(12),
    imgSource: "/Redbull.png",
  },
  {
    productId: NumberInt(3),
    name: "Eivan",
    qty: NumberInt(45),
    price: NumberInt(25),
    imgSource: "/Eivan.png",
  },
  {
    productId: NumberInt(4),
    name: "Fujicha",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Fujicha.png",
  },
  {
    productId: NumberInt(4),
    name: "Gohgae",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Gohgae.png",
  },
  {
    productId: NumberInt(4),
    name: "Sponsor",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Sponsor.png",
  },
  {
    productId: NumberInt(4),
    name: "Sunbite",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Sunbite.png",
  },
  {
    productId: NumberInt(4),
    name: "Pokky",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Pokky.png",
  },
  {
    productId: NumberInt(4),
    name: "Lactasoy",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Lactasoy.png",
  },
  {
    productId: NumberInt(4),
    name: "Mandm",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Mandm.png",
  },
  {
    productId: NumberInt(4),
    name: "Lay",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Lay.png",
  },
  {
    productId: NumberInt(4),
    name: "Sprite",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Sprite.png",
  },
  {
    productId: NumberInt(4),
    name: "Jollybear",
    qty: NumberInt(21),
    price: NumberInt(50),
    imgSource: "/Jollybear.png",
  },
]);
