version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=mongodb://mongodb:27017

  mongodb:
    build: ./mongo_image
    ports:
      - "27017:27017"
